### ISSUE TITLE
i2c overlay

### ISSUE THREAD

**Issue by zuverck** [bigtreetech/BTT-Pi#13]
Trying to determine which pins on the GPIO are tied to the i2c interface.  There is an overlay and i2c device defined in the BoardEnv.tst file but don't see any documentation or notation in the pins diagram on which pins these are connected to on the GPIO header.

**Comment by intplus10** [comment]
It is matching with the standard Pi. I would refer to BTT-Pi user manual page 7, I hope you are searching for this information:
![image](https://github.com/bigtreetech/BTT-Pi/assets/121094484/6acfb1b9-43a6-41f2-8936-3e74d5023722)

**Comment by EidenPride** [comment]
> Trying to determine which pins on the GPIO are tied to the i2c interface. There is an overlay and i2c device defined in the BoardEnv.tst file but don't see any documentation or notation in the pins diagram on which pins these are connected to on the GPIO header.

Hi did you find out something about l2c?

**Comment by BTTJUSTIN** [comment]
Thanks for making this suggestion. We will discuss it internally and update the documentation if it is approved
