### ISSUE TITLE
pdf manual Damaged or Corrupted

### ISSUE THREAD

**Issue by videogramme** [bigtreetech/BTT-Pi#5]
Hello,

I can't open the file on github, my browser, my pdf preview app.
Am'i the only one ?

Regards,

**Comment by So6Rallye** [comment]
I can open it without a problem. Can you download it and open it directly on your computer?

**Comment by videogramme** [comment]
I do not understand, i have no problem with other pdf. This one simply do not work on my osx computer. Just download it, 174Ko (is it the size?) and i can't open it. Even in Adobe Acrobat Pro

**Comment by So6Rallye** [comment]
4.95MB for the pdf. preview work and when it's downloaded I can open it too with classic Adobe.
